package view;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author melkart
 */
public class JPBarraVentana extends javax.swing.JPanel {

    private VentanaPrincipal parent;

    public JPBarraVentana() {
        initComponents();
        iniciarLayout();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPTitulo = new javax.swing.JPanel();
        jLTitulo = new javax.swing.JLabel();
        jPNotificaciones = new javax.swing.JPanel();
        jBNotificaciones = new javax.swing.JButton();
        jPAccionesVentana = new javax.swing.JPanel();
        jBCerrar = new javax.swing.JButton();
        jBMaximizar = new javax.swing.JButton();
        jBMinimizar = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(34000, 25));
        setMinimumSize(new java.awt.Dimension(920, 25));
        setPreferredSize(new java.awt.Dimension(920, 25));

        jPTitulo.setPreferredSize(new java.awt.Dimension(186, 28));

        jLTitulo.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLTitulo.setText("  FunApp");

        javax.swing.GroupLayout jPTituloLayout = new javax.swing.GroupLayout(jPTitulo);
        jPTitulo.setLayout(jPTituloLayout);
        jPTituloLayout.setHorizontalGroup(
            jPTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
        );
        jPTituloLayout.setVerticalGroup(
            jPTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jBNotificaciones.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jBNotificaciones.setFocusPainted(false);
        jBNotificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNotificacionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPNotificacionesLayout = new javax.swing.GroupLayout(jPNotificaciones);
        jPNotificaciones.setLayout(jPNotificacionesLayout);
        jPNotificacionesLayout.setHorizontalGroup(
            jPNotificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPNotificacionesLayout.createSequentialGroup()
                .addComponent(jBNotificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 302, Short.MAX_VALUE))
        );
        jPNotificacionesLayout.setVerticalGroup(
            jPNotificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPNotificacionesLayout.createSequentialGroup()
                .addComponent(jBNotificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jBCerrar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jBCerrar.setFocusPainted(false);
        jBCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCerrarActionPerformed(evt);
            }
        });

        jBMaximizar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jBMaximizar.setFocusPainted(false);

        jBMinimizar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jBMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jBMinimizar.setFocusPainted(false);
        jBMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMinimizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPAccionesVentanaLayout = new javax.swing.GroupLayout(jPAccionesVentana);
        jPAccionesVentana.setLayout(jPAccionesVentanaLayout);
        jPAccionesVentanaLayout.setHorizontalGroup(
            jPAccionesVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPAccionesVentanaLayout.createSequentialGroup()
                .addGap(0, 312, Short.MAX_VALUE)
                .addComponent(jBMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBMaximizar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPAccionesVentanaLayout.setVerticalGroup(
            jPAccionesVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBMinimizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBMaximizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPNotificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPAccionesVentana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
            .addComponent(jPNotificaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPAccionesVentana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBNotificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNotificacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBNotificacionesActionPerformed

    private void jBCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBCerrarActionPerformed

    private void jBMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMinimizarActionPerformed
        this.parent.setExtendedState(this.parent.ICONIFIED);
    }//GEN-LAST:event_jBMinimizarActionPerformed

    private void iniciarLayout() {

        this.setBackground(Color.decode("#012e33"));

        //Sección Título
        this.jPTitulo.setBackground(Color.decode("#012e33"));
        this.jLTitulo.setForeground(Color.decode("#94c8d6"));

        //Sección Notificaciones
        this.jPNotificaciones.setBackground(Color.decode("#012e33"));
        Image imgNotificaciones = new ImageIcon(getClass().getResource("/imagenes/notificacion1.png")).getImage();
        Image imgNotificacionesResc = imgNotificaciones.getScaledInstance(18, 18, java.awt.Image.SCALE_SMOOTH);
        this.jBNotificaciones.setIcon(new ImageIcon(imgNotificacionesResc));
        this.jBNotificaciones.setBackground(Color.decode("#012e33"));
        this.jBNotificaciones.setForeground(Color.decode("#ffffff"));
        this.jBNotificaciones.setContentAreaFilled(false);
        this.jBNotificaciones.setOpaque(true);
        this.jBNotificaciones.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        
        //Sección Acciones de ventana
        this.jPAccionesVentana.setBackground(Color.decode("#012e33"));

        Image imgMinimizar = new ImageIcon(getClass().getResource("/imagenes/minimizar.png")).getImage();
        Image imgMinimizarResc = imgMinimizar.getScaledInstance(15, 15, java.awt.Image.SCALE_SMOOTH);
        this.jBMinimizar.setIcon(new ImageIcon(imgMinimizarResc));
        this.jBMinimizar.setBackground(Color.decode("#012e33"));
        this.jBMinimizar.setForeground(Color.decode("#ffffff"));
        this.jBMinimizar.setContentAreaFilled(false);
        this.jBMinimizar.setOpaque(true);
        this.jBMinimizar.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        Image imgMaximizar = new ImageIcon(getClass().getResource("/imagenes/maximizar.png")).getImage();
        Image imgMaximizarResc = imgMaximizar.getScaledInstance(15, 15, java.awt.Image.SCALE_SMOOTH);
        this.jBMaximizar.setIcon(new ImageIcon(imgMaximizarResc));
        this.jBMaximizar.setBackground(Color.decode("#012e33"));
        this.jBMaximizar.setForeground(Color.decode("#ffffff"));
        this.jBMaximizar.setContentAreaFilled(false);
        this.jBMaximizar.setOpaque(true);
        this.jBMaximizar.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        
        Image imgCerrar = new ImageIcon(getClass().getResource("/imagenes/cerrar.png")).getImage();
        Image imgCerrarResc = imgCerrar.getScaledInstance(15, 15, java.awt.Image.SCALE_SMOOTH);
        this.jBCerrar.setIcon(new ImageIcon(imgCerrarResc));
        this.jBCerrar.setBackground(Color.decode("#012e33"));
        this.jBCerrar.setForeground(Color.decode("#ffffff"));
        this.jBCerrar.setContentAreaFilled(false);
        this.jBCerrar.setOpaque(true);
        this.jBCerrar.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));        
    }

    public void setParent(VentanaPrincipal parent) {
        this.parent = parent;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCerrar;
    private javax.swing.JButton jBMaximizar;
    private javax.swing.JButton jBMinimizar;
    private javax.swing.JButton jBNotificaciones;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JPanel jPAccionesVentana;
    private javax.swing.JPanel jPNotificaciones;
    private javax.swing.JPanel jPTitulo;
    // End of variables declaration//GEN-END:variables

}
