package view;

import com.teamdev.jxbrowser.browser.Browser;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.io.IOException;
import java.util.Calendar;
import java.util.HashSet;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import model.Evento;
import model.Tematica;
import model.Ubicacion;
import model.UsuarioResponsable;
import util.Protocolo;
import util.TextPrompt;

/**
 *
 * @author melkart
 */
public class JPCrearEvento extends javax.swing.JPanel implements Protocolo {

    private VentanaPrincipal parent;
    private JPSesionAbierta vistaSesionAbierta;
    //private JPGoogleMaps jPGoogleMaps;
    private TextPrompt pHNombreEvento;
    private TextPrompt pHDescripcion;
    private TextPrompt pHCalle;
    private TextPrompt pHCodigoPostal;
    private TextPrompt pHDuracion;
    private String mensaje;

    public JPCrearEvento() {
        initComponents();
        iniciarLayout();
        //jPGoogleMaps = new JPGoogleMaps();
        //this.jPGoogleMaps.setSize(700, 240);
        //this.jPMapa.add(jPGoogleMaps);
        //this.jPMapa.revalidate();
        //this.jPMapa.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPPrincipal = new javax.swing.JPanel();
        jLCrearEvento = new javax.swing.JLabel();
        jSeparator = new javax.swing.JSeparator();
        jBConfirmar = new javax.swing.JButton();
        jLImagen = new javax.swing.JLabel();
        jTFnombreEvento = new javax.swing.JTextField();
        jSPDescripcion = new javax.swing.JScrollPane();
        jTADescripcion = new javax.swing.JTextArea();
        jBElegirImagen = new javax.swing.JButton();
        jCBTematica = new javax.swing.JComboBox<>();
        jDCFecha = new datechooser.beans.DateChooserCombo();
        jCBCodigoQR = new javax.swing.JCheckBox();
        jTFCodigoPostal = new javax.swing.JTextField();
        jTFCalle = new javax.swing.JTextField();
        jLMapa = new javax.swing.JLabel();
        jTPHoraInicio = new com.github.lgooddatepicker.components.TimePicker();
        jTPHoraFin = new com.github.lgooddatepicker.components.TimePicker();
        jLHora1 = new javax.swing.JLabel();
        jLHora2 = new javax.swing.JLabel();
        jLFecha = new javax.swing.JLabel();
        jLTematica = new javax.swing.JLabel();
        jPMapa = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(559, 625));

        jPPrincipal.setMinimumSize(new java.awt.Dimension(726, 625));
        jPPrincipal.setPreferredSize(new java.awt.Dimension(726, 625));

        jLCrearEvento.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLCrearEvento.setText("Crear evento");

        jBConfirmar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jBConfirmar.setText("Confirmar");
        jBConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConfirmarActionPerformed(evt);
            }
        });

        jTFnombreEvento.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N

        jTADescripcion.setColumns(20);
        jTADescripcion.setRows(5);
        jSPDescripcion.setViewportView(jTADescripcion);

        jBElegirImagen.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jBElegirImagen.setText("Elegir imagen");

        jCBTematica.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jCBTematica.setSelectedIndex(-1);
        jCBTematica.setBorder(null);

        jDCFecha.setCalendarBackground(new java.awt.Color(254, 254, 254));
        jDCFecha.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jDCFecha.setWeekStyle(datechooser.view.WeekDaysStyle.SHORT);
        jDCFecha.setFieldFont(new java.awt.Font("Ubuntu", java.awt.Font.BOLD, 12));

        jCBCodigoQR.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jCBCodigoQR.setText("Bonificaciones por código QR");

        jTFCodigoPostal.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N

        jTFCalle.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N

        jLMapa.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLMapa.setText("Buscar la ubicación en el mapa");

        jTPHoraInicio.setBorder(null);
        jTPHoraInicio.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        jTPHoraFin.setBorder(null);
        jTPHoraFin.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jTPHoraFin.setOpaque(false);

        jLHora1.setText("desde");

        jLHora2.setText("hasta");

        jLFecha.setText("Fecha ");

        jLTematica.setText("Temática");

        javax.swing.GroupLayout jPMapaLayout = new javax.swing.GroupLayout(jPMapa);
        jPMapa.setLayout(jPMapaLayout);
        jPMapaLayout.setHorizontalGroup(
            jPMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPMapaLayout.setVerticalGroup(
            jPMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 242, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPPrincipalLayout = new javax.swing.GroupLayout(jPPrincipal);
        jPPrincipal.setLayout(jPPrincipalLayout);
        jPPrincipalLayout.setHorizontalGroup(
            jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPMapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator)
                    .addGroup(jPPrincipalLayout.createSequentialGroup()
                        .addComponent(jLCrearEvento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPPrincipalLayout.createSequentialGroup()
                        .addComponent(jTFCalle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFCodigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPPrincipalLayout.createSequentialGroup()
                        .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBElegirImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSPDescripcion)
                            .addGroup(jPPrincipalLayout.createSequentialGroup()
                                .addComponent(jTFnombreEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPPrincipalLayout.createSequentialGroup()
                        .addComponent(jLTematica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBTematica, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPPrincipalLayout.createSequentialGroup()
                        .addComponent(jLFecha)
                        .addGap(6, 6, 6)
                        .addComponent(jDCFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLHora1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTPHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLHora2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTPHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(jCBCodigoQR))
                    .addGroup(jPPrincipalLayout.createSequentialGroup()
                        .addComponent(jLMapa)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPPrincipalLayout.setVerticalGroup(
            jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPrincipalLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCrearEvento)
                    .addComponent(jBConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPPrincipalLayout.createSequentialGroup()
                        .addComponent(jTFnombreEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSPDescripcion))
                    .addGroup(jPPrincipalLayout.createSequentialGroup()
                        .addComponent(jLImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBElegirImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTPHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLHora2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTPHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCBCodigoQR, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDCFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLHora1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBTematica, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTematica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFCodigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLMapa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPMapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConfirmarActionPerformed

        if (textFieldsVacios()) {
            JOptionPane.showMessageDialog(null, "Debes completar todos los campos.");
        } else if (this.jDCFecha.getSelectedDate().before(Calendar.getInstance())) {
            JOptionPane.showMessageDialog(null, "Hay que señalar una fecha posterior a la de hoy.");
        } else {

            try {

                Integer protocolo = INSERTAR_EVENTO;
                this.mensaje = this.parent.getGson().toJson(protocolo);
                this.parent.getSalida().writeUTF(this.mensaje);

                Tematica tematica = (Tematica) this.jCBTematica.getSelectedItem();
                Ubicacion ubicacion = new Ubicacion(
                        0, this.jTFCalle.getText(),
                        Integer.parseInt(this.jTFCodigoPostal.getText()), 0.0, 0.0);

                HashSet<Ubicacion> ubicaciones = new HashSet<Ubicacion>();
                ubicaciones.add(ubicacion);
                Evento evento = new Evento(
                        0, this.jTFnombreEvento.getText(), null, this.jDCFecha.getSelectedDate().getTime(),
                        this.jTPHoraInicio.getTime(), this.jTPHoraFin.getTime(),
                        ubicaciones, tematica, (UsuarioResponsable) this.parent.getUsuario()
                );

                this.mensaje = this.parent.getGson().toJson(evento);
                this.parent.getSalida().writeUTF(this.mensaje);
                this.mensaje = (String) this.parent.getEntrada().readUTF();
                this.parent.setEstadoSesion((Integer) this.parent.getGson().fromJson(this.mensaje, Integer.class));
                if (this.parent.getEstadoSesion() == INSERTAR_EXITO) {
                    JOptionPane.showMessageDialog(null, "El evento se ha añadido con éxito.");
                    this.parent.setEstadoSesion(SESION_ABIERTA_RESPONSABLE);
                    this.vistaSesionAbierta.vistaInicio();
                } else if (this.parent.getEstadoSesion() == INSERTAR_FALLIDO) {
                    JOptionPane.showMessageDialog(null, "No se ha podido insertar el evento.");
                }

            } catch (IOException ex) {
            }
        }
    }//GEN-LAST:event_jBConfirmarActionPerformed

    private void iniciarLayout() {

        this.setBackground(Color.decode("#012326"));
        this.jPPrincipal.setBackground(Color.decode("#012326"));

        this.jLCrearEvento.setForeground(Color.decode("#ffffff"));
        this.jBConfirmar.setBackground(Color.decode("#94c8d6"));
        this.jBConfirmar.setOpaque(true);
        this.jBConfirmar.setHorizontalAlignment(SwingConstants.CENTER);
        this.jBConfirmar.setBorder(BorderFactory.createLineBorder(Color.decode("#94c8d6")));
        this.jBConfirmar.setForeground(Color.decode("#f2f2f2"));
        this.jBConfirmar.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        this.jBConfirmar.setFocusPainted(false);

        this.jSeparator.setBackground(Color.decode("#d64d55"));
        this.jSeparator.setForeground(Color.decode("#d64d55"));

        this.jLImagen.setOpaque(true);
        this.jLImagen.setBorder(BorderFactory.createLineBorder(Color.decode("#94c8d6")));

        this.jBElegirImagen.setBackground(Color.decode("#94c8d6"));
        this.jBElegirImagen.setOpaque(true);
        this.jBElegirImagen.setHorizontalAlignment(SwingConstants.CENTER);
        this.jBElegirImagen.setBorder(BorderFactory.createLineBorder(Color.decode("#94c8d6")));
        this.jBElegirImagen.setForeground(Color.decode("#f2f2f2"));
        this.jBElegirImagen.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        this.jBElegirImagen.setFocusPainted(false);

        this.jLFecha.setForeground(Color.decode("#f2f2f2"));
        this.jLHora1.setForeground(Color.decode("#f2f2f2"));
        this.jLHora2.setForeground(Color.decode("#f2f2f2"));
        this.jLTematica.setForeground(Color.decode("#f2f2f2"));
        this.jCBTematica.setBorder(BorderFactory.createLineBorder(Color.decode("#ffffff")));
        this.jDCFecha.setBorder(BorderFactory.createLineBorder(Color.decode("#ffffff")));
        this.jTPHoraInicio.setBorder(BorderFactory.createLineBorder(Color.decode("#ffffff")));
        this.jTPHoraFin.setBorder(BorderFactory.createLineBorder(Color.decode("#ffffff")));
        this.jCBCodigoQR.setForeground(Color.decode("#f2f2f2"));
        this.jCBCodigoQR.setBackground(Color.decode("#012e33"));
        this.jCBCodigoQR.setContentAreaFilled(false);
        this.jCBCodigoQR.setFocusPainted(false);

        this.jDCFecha.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        this.jTPHoraInicio.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        this.jTPHoraFin.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        this.jCBTematica.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        //Configuración de los campos de textos y agregar placehorder
        this.jTFnombreEvento.setBorder(BorderFactory.createLineBorder(Color.decode("#ffffff")));
        this.pHNombreEvento = new TextPrompt("Nombre del evento", this.jTFnombreEvento);
        this.pHNombreEvento.changeAlpha(0.75f);
        this.pHNombreEvento.changeStyle(Font.ITALIC);

        this.jSPDescripcion.setBorder(BorderFactory.createLineBorder(Color.decode("#ffffff")));
        this.jTADescripcion.setBorder(BorderFactory.createLineBorder(Color.decode("#ffffff")));
        this.pHDescripcion = new TextPrompt("Descripción", this.jTADescripcion);
        this.pHDescripcion.changeAlpha(0.75f);
        this.pHDescripcion.changeStyle(Font.ITALIC);

        this.jTFCalle.setBorder(BorderFactory.createLineBorder(Color.decode("#ffffff")));
        this.pHCalle = new TextPrompt("Calle/vía", this.jTFCalle);
        this.pHCalle.changeAlpha(0.75f);
        this.pHCalle.changeStyle(Font.ITALIC);

        this.jTFCodigoPostal.setBorder(BorderFactory.createLineBorder(Color.decode("#ffffff")));
        this.pHCodigoPostal = new TextPrompt("Código postal", this.jTFCodigoPostal);
        this.pHCodigoPostal.changeAlpha(0.75f);
        this.pHCodigoPostal.changeStyle(Font.ITALIC);

        this.jLMapa.setForeground(Color.decode("#ffffff"));

    }

    public boolean textFieldsVacios() {

        boolean[] fields = new boolean[8];
        boolean vacio = false;
        fields[0] = this.jTFnombreEvento.getText().isEmpty();
        fields[1] = this.jTADescripcion.getText().isEmpty();
        fields[2] = this.jTFCalle.getText().isEmpty();
        fields[3] = this.jTFCodigoPostal.getText().isEmpty();

        for (int i = 0; fields.length < i; i++) {
            if (fields[i]) {
                vacio = true;
            }
        }
        return vacio;
    }

    public void llenarCBTematica() {

        for (int i = 0; i < this.parent.getTematicas().size(); i++) {
            this.jCBTematica.addItem((Tematica) this.parent.getTematicas().get(i));
        }
    }

    public void setParent(VentanaPrincipal parent) {
        this.parent = parent;
    }

    public void setJPSesionAbierta(JPSesionAbierta jPSesionAbierta) {
        this.vistaSesionAbierta = jPSesionAbierta;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConfirmar;
    private javax.swing.JButton jBElegirImagen;
    private javax.swing.JCheckBox jCBCodigoQR;
    private javax.swing.JComboBox<Tematica> jCBTematica;
    private datechooser.beans.DateChooserCombo jDCFecha;
    private javax.swing.JLabel jLCrearEvento;
    private javax.swing.JLabel jLFecha;
    private javax.swing.JLabel jLHora1;
    private javax.swing.JLabel jLHora2;
    private javax.swing.JLabel jLImagen;
    private javax.swing.JLabel jLMapa;
    private javax.swing.JLabel jLTematica;
    private javax.swing.JPanel jPMapa;
    private javax.swing.JPanel jPPrincipal;
    private javax.swing.JScrollPane jSPDescripcion;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JTextArea jTADescripcion;
    private javax.swing.JTextField jTFCalle;
    private javax.swing.JTextField jTFCodigoPostal;
    private javax.swing.JTextField jTFnombreEvento;
    private com.github.lgooddatepicker.components.TimePicker jTPHoraFin;
    private com.github.lgooddatepicker.components.TimePicker jTPHoraInicio;
    // End of variables declaration//GEN-END:variables
}
