/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.Tematica;

/**
 *
 * @author melkart
 */
public class JPEditarEvento extends javax.swing.JPanel {

    /**
     * Creates new form EditarEvento
     */
    public JPEditarEvento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPPrincipal = new javax.swing.JPanel();
        jLCrearEvento = new javax.swing.JLabel();
        jSeparator = new javax.swing.JSeparator();
        jBConfirmar = new javax.swing.JButton();
        jTFnombreEvento = new javax.swing.JTextField();
        jSPDescripcion = new javax.swing.JScrollPane();
        jTADescripcion = new javax.swing.JTextArea();
        jCBTematica = new javax.swing.JComboBox<>();
        jDCFecha = new datechooser.beans.DateChooserCombo();
        jCBCodigoQR = new javax.swing.JCheckBox();
        jTFCodigoPostal = new javax.swing.JTextField();
        jTFCalle = new javax.swing.JTextField();
        jTPHoraInicio = new com.github.lgooddatepicker.components.TimePicker();
        jTPHoraFin = new com.github.lgooddatepicker.components.TimePicker();
        jLHora1 = new javax.swing.JLabel();
        jLHora2 = new javax.swing.JLabel();
        jLFecha = new javax.swing.JLabel();
        jLTematica = new javax.swing.JLabel();
        jLInfo1 = new javax.swing.JLabel();
        jLInfo2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(559, 625));

        jPPrincipal.setMinimumSize(new java.awt.Dimension(726, 625));

        jLCrearEvento.setText("Editar evento");
        jLCrearEvento.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N

        jBConfirmar.setText("Actualizar");
        jBConfirmar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jBConfirmar.setPreferredSize(new java.awt.Dimension(726, 625));
        jBConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConfirmarActionPerformed(evt);
            }
        });

        jTFnombreEvento.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N

        jTADescripcion.setColumns(20);
        jTADescripcion.setRows(5);
        jSPDescripcion.setViewportView(jTADescripcion);

        jCBTematica.setBorder(null);
        jCBTematica.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jCBTematica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBTematicaActionPerformed(evt);
            }
        });

        jDCFecha.setCalendarBackground(new java.awt.Color(254, 254, 254));
        jDCFecha.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jDCFecha.setWeekStyle(datechooser.view.WeekDaysStyle.SHORT);
        jDCFecha.setFieldFont(new java.awt.Font("Ubuntu", java.awt.Font.BOLD, 12));

        jCBCodigoQR.setText("Bonificaciones por código QR");
        jCBCodigoQR.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N

        jTFCodigoPostal.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N

        jTFCalle.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N

        jTPHoraInicio.setBorder(null);
        jTPHoraInicio.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        jTPHoraFin.setBorder(null);
        jTPHoraFin.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jTPHoraFin.setOpaque(false);

        jLHora1.setText("desde");

        jLHora2.setText("hasta");

        jLFecha.setText("Fecha ");

        jLTematica.setText("Temática");

        jLInfo1.setFont(new java.awt.Font("Ubuntu", 2, 15)); // NOI18N
        jLInfo1.setText("*Recuerda que desde nuestra aplicación móvil podrás tener una experiencia más cercana con los usuarios  ");

        jLInfo2.setFont(new java.awt.Font("Ubuntu", 2, 15)); // NOI18N
        jLInfo2.setText("asistentes mediante las publicaciones de evento y las valoraciones de los usuarios.");

        javax.swing.GroupLayout jPPrincipalLayout = new javax.swing.GroupLayout(jPPrincipal);
        jPPrincipal.setLayout(jPPrincipalLayout);
        jPPrincipalLayout.setHorizontalGroup(
            jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSPDescripcion, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPPrincipalLayout.createSequentialGroup()
                        .addComponent(jTFCalle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFCodigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPPrincipalLayout.createSequentialGroup()
                        .addComponent(jLTematica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBTematica, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPPrincipalLayout.createSequentialGroup()
                        .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLCrearEvento)
                            .addComponent(jTFnombreEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLInfo1)
                            .addComponent(jLInfo2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPPrincipalLayout.createSequentialGroup()
                        .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPPrincipalLayout.createSequentialGroup()
                                .addComponent(jLFecha)
                                .addGap(6, 6, 6)
                                .addComponent(jDCFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLHora1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTPHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLHora2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTPHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jBConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(jCBCodigoQR)))
                .addContainerGap())
        );
        jPPrincipalLayout.setVerticalGroup(
            jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPrincipalLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLCrearEvento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTFnombreEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSPDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFCodigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 21, Short.MAX_VALUE)
                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBTematica, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTematica))
                .addGap(18, 18, 18)
                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTPHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLHora2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTPHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCBCodigoQR, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDCFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLHora1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jBConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLInfo1)
                .addGap(0, 0, 0)
                .addComponent(jLInfo2)
                .addGap(164, 164, 164))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConfirmarActionPerformed

    /*    if (textFieldsVacios()) {
            JOptionPane.showMessageDialog(null, "Debes completar todos los campos.");
        } else if (this.jDCFecha.getSelectedDate().before(Calendar.getInstance())) {
            JOptionPane.showMessageDialog(null, "Hay que señalar una fecha posterior a la de hoy.");
        } else {

            try {

                Integer protocolo = INSERTAR_EVENTO;
                this.mensaje = this.parent.getGson().toJson(protocolo);
                this.parent.getSalida().writeUTF(this.mensaje);

                Tematica tematica = (Tematica) this.jCBTematica.getSelectedItem();
                Ubicacion ubicacion = new Ubicacion(
                    0, this.jTFCalle.getText(),
                    this.jTFCodigoPostal.getText(), 0.0, 0.0);

                HashSet<Ubicacion> ubicaciones = new HashSet<Ubicacion>();
                ubicaciones.add(ubicacion);
                Evento evento = new Evento(
                    0, this.jTFnombreEvento.getText(), this.jTADescripcion.getText(), null, this.jDCFecha.getSelectedDate().getTime(),
                    this.jTPHoraInicio.getTime(), this.jTPHoraFin.getTime(),
                    ubicaciones, null, tematica, (UsuarioResponsable) this.parent.getUsuario(), true
                );

                this.mensaje = this.parent.getGson().toJson(evento);
                this.parent.getSalida().writeUTF(this.mensaje);
                this.mensaje = (String) this.parent.getEntrada().readUTF();
                this.parent.setEstadoSesion((Integer) this.parent.getGson().fromJson(this.mensaje, Integer.class));
                if (this.parent.getEstadoSesion() == INSERTAR_EXITO) {
                    JOptionPane.showMessageDialog(null, "El evento se ha añadido con éxito.");
                    this.parent.setEstadoSesion(SESION_ABIERTA_RESPONSABLE);
                    this.vistaSesionAbierta.vistaMisEventos();
                } else if (this.parent.getEstadoSesion() == INSERTAR_FALLIDO) {
                    JOptionPane.showMessageDialog(null, "No se ha podido insertar el evento.");
                }

            } catch (IOException ex) {
            }
        }*/
    }//GEN-LAST:event_jBConfirmarActionPerformed

    private void jCBTematicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBTematicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBTematicaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConfirmar;
    private javax.swing.JCheckBox jCBCodigoQR;
    private javax.swing.JComboBox<Tematica> jCBTematica;
    private datechooser.beans.DateChooserCombo jDCFecha;
    private javax.swing.JLabel jLCrearEvento;
    private javax.swing.JLabel jLFecha;
    private javax.swing.JLabel jLHora1;
    private javax.swing.JLabel jLHora2;
    private javax.swing.JLabel jLInfo1;
    private javax.swing.JLabel jLInfo2;
    private javax.swing.JLabel jLTematica;
    private javax.swing.JPanel jPPrincipal;
    private javax.swing.JScrollPane jSPDescripcion;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JTextArea jTADescripcion;
    private javax.swing.JTextField jTFCalle;
    private javax.swing.JTextField jTFCodigoPostal;
    private javax.swing.JTextField jTFnombreEvento;
    private com.github.lgooddatepicker.components.TimePicker jTPHoraFin;
    private com.github.lgooddatepicker.components.TimePicker jTPHoraInicio;
    // End of variables declaration//GEN-END:variables
}
