
package view;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;

/**
 *
 * @author melkart
 */
public class JPMenu extends javax.swing.JPanel {

    private JPSesionAbierta parent;
    private JPCrearEvento vistaCrearEvento;

    public JPMenu() {
        initComponents();
        iniciarLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPSecciones = new javax.swing.JPanel();
        jBMisEventos = new javax.swing.JButton();
        jBCrearEvento = new javax.swing.JButton();
        jBSeguidores = new javax.swing.JButton();
        jBHistorial = new javax.swing.JButton();

        jBMisEventos.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jBMisEventos.setText("   Mis eventos");
        jBMisEventos.setBorder(null);
        jBMisEventos.setFocusPainted(false);
        jBMisEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMisEventosActionPerformed(evt);
            }
        });

        jBCrearEvento.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jBCrearEvento.setText("   Crear evento");
        jBCrearEvento.setBorder(null);
        jBCrearEvento.setFocusPainted(false);
        jBCrearEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCrearEventoActionPerformed(evt);
            }
        });

        jBSeguidores.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jBSeguidores.setText("   Cuenta");
        jBSeguidores.setBorder(null);
        jBSeguidores.setFocusPainted(false);
        jBSeguidores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSeguidoresActionPerformed(evt);
            }
        });

        jBHistorial.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jBHistorial.setText("   Historial");
        jBHistorial.setBorder(null);
        jBHistorial.setFocusPainted(false);
        jBHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBHistorialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPSeccionesLayout = new javax.swing.GroupLayout(jPSecciones);
        jPSecciones.setLayout(jPSeccionesLayout);
        jPSeccionesLayout.setHorizontalGroup(
            jPSeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSeccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPSeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBSeguidores)
                    .addComponent(jBCrearEvento)
                    .addComponent(jBMisEventos)
                    .addComponent(jBHistorial))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPSeccionesLayout.setVerticalGroup(
            jPSeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSeccionesLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jBMisEventos)
                .addGap(42, 42, 42)
                .addComponent(jBCrearEvento)
                .addGap(42, 42, 42)
                .addComponent(jBHistorial)
                .addGap(42, 42, 42)
                .addComponent(jBSeguidores)
                .addContainerGap(196, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPSecciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPSecciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBCrearEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCrearEventoActionPerformed
        this.parent.vistaCrearEvento();
        
    }//GEN-LAST:event_jBCrearEventoActionPerformed

    private void jBMisEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMisEventosActionPerformed
        this.parent.vistaMisEventos();
    }//GEN-LAST:event_jBMisEventosActionPerformed

    private void jBHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBHistorialActionPerformed
        this.parent.vistaHistorial();
    }//GEN-LAST:event_jBHistorialActionPerformed

    private void jBSeguidoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSeguidoresActionPerformed
        this.parent.vistaCuenta();
    }//GEN-LAST:event_jBSeguidoresActionPerformed

    private void iniciarLayout() {

        this.setBackground(Color.decode("#012e33"));

        //Sección Menú
        this.jPSecciones.setBackground(Color.decode("#012e33"));

        Image imgMisEventos = new ImageIcon(getClass().getResource("/imagenes/mis_eventos.png")).getImage();
        Image imgMisEventosResc = imgMisEventos.getScaledInstance(30, 30, java.awt.Image.SCALE_SMOOTH);
        this.jBMisEventos.setIcon(new ImageIcon(imgMisEventosResc));
        this.jBMisEventos.setBackground(Color.decode("#012e33"));
        this.jBMisEventos.setForeground(Color.decode("#ffffff"));
        this.jBMisEventos.setContentAreaFilled(false);
        this.jBMisEventos.setOpaque(true);
        this.jBMisEventos.setHorizontalTextPosition(SwingConstants.RIGHT);
        this.jBMisEventos.setVerticalTextPosition(SwingConstants.CENTER);
        this.jBMisEventos.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        Image imgCrearEvento = new ImageIcon(getClass().getResource("/imagenes/crear_evento.png")).getImage();
        Image imgCrearEventoResc = imgCrearEvento.getScaledInstance(30, 30, java.awt.Image.SCALE_SMOOTH);
        this.jBCrearEvento.setIcon(new ImageIcon(imgCrearEventoResc));
        this.jBCrearEvento.setBackground(Color.decode("#012e33"));
        this.jBCrearEvento.setForeground(Color.decode("#ffffff"));
        this.jBCrearEvento.setContentAreaFilled(false);
        this.jBCrearEvento.setOpaque(true);
        this.jBCrearEvento.setHorizontalTextPosition(SwingConstants.RIGHT);
        this.jBCrearEvento.setVerticalTextPosition(SwingConstants.CENTER);
        this.jBCrearEvento.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        Image imgCuenta = new ImageIcon(getClass().getResource("/imagenes/cuenta.png")).getImage();
        Image imgCuentaResc = imgCuenta.getScaledInstance(30, 30, java.awt.Image.SCALE_SMOOTH);
        this.jBSeguidores.setIcon(new ImageIcon(imgCuentaResc));
        this.jBSeguidores.setBackground(Color.decode("#012e33"));
        this.jBSeguidores.setForeground(Color.decode("#ffffff"));
        this.jBSeguidores.setContentAreaFilled(false);
        this.jBSeguidores.setOpaque(true);
        this.jBSeguidores.setHorizontalTextPosition(SwingConstants.RIGHT);
        this.jBSeguidores.setVerticalTextPosition(SwingConstants.CENTER);
        this.jBSeguidores.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        Image imgHistorial = new ImageIcon(getClass().getResource("/imagenes/historial.png")).getImage();
        Image imgHistorialResc = imgHistorial.getScaledInstance(30, 30, java.awt.Image.SCALE_SMOOTH);
        this.jBHistorial.setIcon(new ImageIcon(imgHistorialResc));
        this.jBHistorial.setBackground(Color.decode("#012e33"));
        this.jBHistorial.setForeground(Color.decode("#ffffff"));
        this.jBHistorial.setContentAreaFilled(false);
        this.jBHistorial.setOpaque(true);
        this.jBHistorial.setHorizontalTextPosition(SwingConstants.RIGHT);
        this.jBHistorial.setVerticalTextPosition(SwingConstants.CENTER);
        this.jBHistorial.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }

    public void setParent(JPSesionAbierta parent) {
        this.parent = parent;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCrearEvento;
    private javax.swing.JButton jBHistorial;
    private javax.swing.JButton jBMisEventos;
    private javax.swing.JButton jBSeguidores;
    private javax.swing.JPanel jPSecciones;
    // End of variables declaration//GEN-END:variables
}
